### ISSUE TITLE
Public commandWait?

### ISSUE THREAD

**Issue by fireblue** [Stericson/RootShell#19]
I've noticed in RootShell.java, there's 
`// --------------------
  // # Public Methods #
  // --------------------
  private static void commandWait(Shell shell, Command cmd) throws Exception `
It's in "Public Methods" section while the method itself is private. This method is quite useful, should it be public?

**Comment by Stericson** [comment]
Hi Fireblue,

The reason that this function isn't private is because it's generally bad practice to block the main thread while performing long running operations.

Really, you should be threading your commands and then relying on callbacks in order to know when it's completed. Feel free to copy the method and use it in your project, but unless you are using threads, I'd be careful about it's usage as it will likely lead to a negative experience for your end users (IE causing an ANR)
