### ISSUE TITLE
Does not work on Android 6

### ISSUE THREAD

**Issue by maxbusko** [Stericson/RootShell#8]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.hardware.input.IInputManager.injectInputEvent(android.view.InputEvent, int)' on a null object reference 
at android.hardware.input.InputManager.injectInputEvent(InputManager.java:679)
at com.android.commands.input.Input.injectMotionEvent(Input.java:259)
at com.android.commands.input.Input.sendTap(Input.java:197)
at com.android.commands.input.Input.run(Input.java:104)
at com.android.commands.input.Input.main(Input.java:59)

**Comment by rahulkumar66** [comment]
this issue can be closed since it's fixed

**Comment by zafersn** [comment]
Did you fix the problem?

**Comment by rahulkumar66** [comment]
yes the issue is fixed

**Comment by zafersn** [comment]
Will it work on Android 7.1?

**Comment by rahulkumar66** [comment]
yes

**Comment by zafersn** [comment]
When I try to use the RootShell I get an error like.

12-15 16:50:02.380 4980-4980/com.stackcuriosity.tooght W/System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.Runtime.exec(Runtime.java:691)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.Runtime.exec(Runtime.java:524)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.Runtime.exec(Runtime.java:421)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stericson.RootShell.execution.Shell.<init>(Shell.java:144)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:848)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stericson.RootShell.RootShell.getShell(RootShell.java:300)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stericson.RootShell.RootShell.getShell(RootShell.java:337)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stericson.RootShell.RootShell.getShell(RootShell.java:347)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.stackcuriosity.tooght.activity.MainActivityFragment.onCreate(MainActivityFragment.java:154)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.os.Looper.loop(Looper.java:154)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-15 16:50:02.381 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err: Caused by: java.io.IOException: error=13, Permission denied
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.UNIXProcess.forkAndExec(Native Method)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.ProcessImpl.start(ProcessImpl.java:128)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
12-15 16:50:02.382 4980-4980/com.stackcuriosity.tooght W/System.err: 	... 21 more

**Comment by Stericson** [comment]
Permission Denied error when trying to exec the su binary likely indicates that the su binary doesn't exist or it lacks proper permissions.
